'use client'
import { useState } from 'react'
import { supabase } from '../../../lib/supabase'

export default function SettingsPage() {
  const [loading, setLoading] = useState(false)
  const [message, setMessage] = useState('')
  
  // State to manage which modal is currently open
  const [activeModal, setActiveModal] = useState(null)

  const handleLogout = async () => {
    await supabase.auth.signOut()
    window.location.href = '/login'
  }

  const handleChangePassword = async () => {
    setLoading(true)
    const { data: { user } } = await supabase.auth.getUser()
    const { error } = await supabase.auth.resetPasswordForEmail(user.email)
    if (error) {
      setMessage('Something went wrong. Please try again.')
    } else {
      setMessage('Password reset email sent! Check your inbox.')
    }
    setLoading(false)
  }

  // Content for the legal modals
  const modalContent = {
    about: {
      title: "About SignalHealth",
      text: `SignalHealth is a proactive AI health companion built by Hannah Brotheridge.

The app regularly checks in with users to understand how they are feeling, tracks ongoing health trends, builds a personalized health profile, and helps organize information into a clear summary for General Practitioner (GP) appointments.

Designed intentionally for elderly accessibility, SignalHealth balances high-contrast layouts, clean mobile interfaces, and supportive technology to ensure your vital health observations are never missed or forgotten during brief doctor consultations.`
    },
    disclaimer: {
      title: "Medical Disclaimer",
      text: `SignalHealth - Medical Disclaimer

1. Not Medical Advice
SignalHealth is an artificial intelligence companion designed to assist you in tracking your personal health narrative and preparing summaries for your doctor. It does not provide medical advice, professional diagnosis, opinion, treatment, or services.

2. No Doctor-Patient Relationship
Your use of SignalHealth does not create a doctor-patient relationship between you and SignalHealth or its developers. The application is a tool to support, not replace, the relationship that exists between you and your general practitioner or other qualified healthcare professionals.

3. Do Not Delay Seeking Care
If you think you may have a medical emergency, call 111 (in New Zealand) or go to the nearest emergency room immediately. You should never disregard professional medical advice or delay seeking medical treatment because of something you have read or processed through SignalHealth.

4. Limitation of AI Capability
The health summaries and insights generated by SignalHealth are based on information you provide and are processed via artificial intelligence. AI can make mistakes, overlook nuances, or misinterpret descriptions. Always review your generated summaries carefully before sharing them with a medical professional.`
    },
    privacy: {
      title: "Privacy Policy",
      text: `SignalHealth - Privacy Policy
Last Updated: June 2026

1. Commitment to Privacy
We respect your privacy and are committed to protecting your personal and health information. This Privacy Policy explains how SignalHealth collects, uses, and safeguards your data in strict compliance with the New Zealand Privacy Act 2020 and the Health Information Privacy Code 2020.

2. Information We Collect
To provide our services, we collect the following information:
- Account Information: Your email and password provided during sign-up.
- Profile Information: Name, age, gender, ethnicity, medications, known health conditions, allergies, lifestyle factors, and medical history.
- Conversation Logs: The text-based chat messages exchanged between you and the SignalHealth AI companion.

3. How We Use Your Information
We use your information solely to:
- Maintain your personal health profile and history.
- Provide interactive AI conversations to help track your well-being.
- Generate structured GP summaries upon your direct request.
We do not sell, rent, or trade your personal or health data to any third parties.

4. Data Processing and Storage
Your profile information and chat history are securely stored in our database. Text information from your conversations is processed via secure Application Programming Interfaces (APIs) to generate your health summaries. Data processed through these APIs is protected under strict commercial privacy terms and is not used to train public AI models.

5. Your Rights Under New Zealand Law
In accordance with the New Zealand Privacy Act 2020, you have the right to request access to any personal information we hold about you and to request corrections to that information. You can update your profile details or change your password directly within the application settings at any time.

6. Contact Us
If you have any questions about this Privacy Policy or wish to exercise your data access rights, please contact the developer via the official project channels.`
    },
    terms: {
      title: "Terms of Service",
      text: `SignalHealth - Terms of Service
Last Updated: June 2026

1. Acceptance of Terms
By accessing or using SignalHealth, you agree to be bound by these Terms of Service. If you do not agree to these terms, you must not use this application.

2. Description of Service
SignalHealth is a proactive AI health companion web application designed to help users track health insights, build a personal health profile, and organize summaries to assist with general practitioner (GP) consultations. SignalHealth does not provide medical advice, diagnosis, or treatment.

3. Eligibility and Accounts
You must provide accurate and complete information when creating an account. You are solely responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.

4. User Conduct and Responsibilities
You agree to use SignalHealth only for lawful personal purposes. You must not use the service to input false, malicious, or intentionally misleading health data. 

5. Limitation of Liability
SignalHealth is provided on an as-is and as-available basis. To the maximum extent permitted by New Zealand law, SignalHealth and its developer shall not be liable for any direct, indirect, incidental, or consequential damages arising out of your use or inability to use the service.

6. Changes to Terms
We reserve the right to modify these terms at any time. Continued use of the application after changes are made constitutes your acceptance of the updated terms.`
    }
  }

  return (
    <div className="flex flex-col min-h-screen pb-20 bg-gray-50">
      <div className="bg-white border-b border-gray-100 px-4 py-4">
        <h1 className="text-xl font-semibold text-gray-900">Settings</h1>
      </div>

      <div className="px-4 py-4 space-y-4 max-w-2xl mx-auto w-full">

        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
          <div className="px-4 py-3 border-b border-gray-50">
            <h2 className="text-base font-semibold text-gray-800">Account</h2>
          </div>
          <button onClick={handleChangePassword} disabled={loading} className="w-full px-4 py-4 flex justify-between items-center border-b border-gray-50 hover:bg-gray-50 transition-colors">
            <span className="text-base text-gray-700">Change Password</span>
            <span className="text-gray-300">›</span>
          </button>
          <button onClick={handleLogout} className="w-full px-4 py-4 flex justify-between items-center hover:bg-gray-50 transition-colors">
            <span className="text-base text-red-500">Sign Out</span>
            <span className="text-gray-300">›</span>
          </button>
        </div>

        {message && (
          <p className="text-sm text-emerald-600 text-center font-medium bg-emerald-50 py-2.5 px-4 rounded-xl border border-emerald-100">{message}</p>
        )}

        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
          <div className="px-4 py-3 border-b border-gray-50">
            <h2 className="text-base font-semibold text-gray-800">Information</h2>
          </div>
          <button onClick={() => setActiveModal('about')} className="w-full px-4 py-4 flex justify-between items-center border-b border-gray-50 hover:bg-gray-50 transition-colors">
            <span className="text-base text-gray-700">About SignalHealth</span>
            <span className="text-gray-300">›</span>
          </button>
          <button onClick={() => setActiveModal('disclaimer')} className="w-full px-4 py-4 flex justify-between items-center border-b border-gray-50 hover:bg-gray-50 transition-colors">
            <span className="text-base text-gray-700">Medical Disclaimer</span>
            <span className="text-gray-300">›</span>
          </button>
          <button onClick={() => setActiveModal('privacy')} className="w-full px-4 py-4 flex justify-between items-center border-b border-gray-50 hover:bg-gray-50 transition-colors">
            <span className="text-base text-gray-700">Privacy Policy</span>
            <span className="text-gray-300">›</span>
          </button>
          <button onClick={() => setActiveModal('terms')} className="w-full px-4 py-4 flex justify-between items-center hover:bg-gray-50 transition-colors">
            <span className="text-base text-gray-700">Terms of Service</span>
            <span className="text-gray-300">›</span>
          </button>
        </div>

        <p className="text-xs text-gray-400 text-center">SignalHealth v1.0 — Built with care</p>

      </div>

      {/* Pop-up Info Modal Component */}
      {activeModal && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4 animate-fade-in">
          <div className="bg-white w-full max-w-2xl rounded-t-3xl sm:rounded-2xl max-h-[85vh] sm:max-h-[80vh] flex flex-col shadow-xl">
            
            {/* Modal Header */}
            <div className="px-6 py-4 border-b border-gray-100 flex justify-between items-center bg-gray-50 rounded-t-3xl sm:rounded-t-2xl">
              <h2 className="text-lg font-bold text-gray-900">{modalContent[activeModal].title}</h2>
              <button 
                onClick={() => setActiveModal(null)}
                className="w-8 h-8 rounded-full bg-gray-200 text-gray-700 flex items-center justify-center text-lg font-bold hover:bg-gray-300 transition-colors"
                aria-label="Close"
              >
                ✕
              </button>
            </div>

            {/* Modal Scrollable Text Content */}
            <div className="p-6 overflow-y-auto text-left">
              <pre className="whitespace-pre-wrap font-sans text-base text-gray-700 leading-relaxed tracking-normal">
                {modalContent[activeModal].text}
              </pre>
            </div>

            {/* Modal Footer Close Button */}
            <div className="p-4 border-t border-gray-100 bg-white sticky bottom-0">
              <button 
                onClick={() => setActiveModal(null)}
                className="w-full py-3.5 bg-emerald-600 hover:bg-emerald-700 text-white font-semibold text-base rounded-xl transition-colors shadow-sm"
              >
                Close Window
              </button>
            </div>

          </div>
        </div>
      )}
    </div>
  )
}